apiVersion: server.example.com/v1alpha1
kind: Nginx
metadata:
  labels:
    app.kubernetes.io/name: nginx-operator
    app.kubernetes.io/managed-by: kustomize
  name: nginx-sample
spec:
  # TODO(user): Add fields here
  size: 1
  version: "1.27.3"
